name: Kernel CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build kernel
      run: make -j$(nproc)
    - name: Build modules
      run: make -j$(nproc) modules
